# Generated by Django 5.2.8 on 2025-11-09 21:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the destination', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of name (auto-generated)', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Full description of the destination')),
                ('short_description', models.CharField(help_text='Brief description for cards and previews', max_length=500)),
                ('country', models.CharField(db_index=True, help_text='Country where destination is located', max_length=100)),
                ('region', models.CharField(blank=True, help_text='Region or state (e.g., Northern Tanzania)', max_length=100)),
                ('latitude', models.DecimalField(decimal_places=6, help_text='Latitude coordinate (-90 to 90)', max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(decimal_places=6, help_text='Longitude coordinate (-180 to 180)', max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('featured_image', models.ImageField(help_text='Main image for the destination', upload_to='destinations/featured/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo video URL (optional)')),
                ('best_time_to_visit', models.CharField(blank=True, help_text="Best months to visit (e.g., 'June - October')", max_length=100)),
                ('climate', models.TextField(blank=True, help_text='Climate information and weather patterns')),
                ('wildlife', models.TextField(blank=True, help_text='Wildlife commonly seen in this destination')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Display on homepage as featured destination')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Published and visible to public')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times this destination was viewed')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title (optional, defaults to name)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destinations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Destination',
                'verbose_name_plural': 'Destinations',
                'ordering': ['order', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DestinationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image', upload_to='destinations/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Image caption (optional)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Destination Image',
                'verbose_name_plural': 'Destination Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['name'], name='destination_name_96ccc3_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['country'], name='destination_country_2ade19_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['is_featured', 'is_active'], name='destination_is_feat_30ec6f_idx'),
        ),
        migrations.AddIndex(
            model_name='destination',
            index=models.Index(fields=['order'], name='destination_order_5dbcec_idx'),
        ),
    ]
