# Generated by Django 5.2.8 on 2026-05-14 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('subject', models.CharField(blank=True, default='General Inquiry', max_length=200)),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('archived', 'Archived')], db_index=True, default='new', max_length=20)),
                ('admin_notes', models.TextField(blank=True, help_text='Private notes for staff (not visible to customer)', verbose_name='Internal Notes')),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, help_text='IP address of submitter (for spam prevention)', null=True)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='core_contac_status_a0adbc_idx'), models.Index(fields=['email'], name='core_contac_email_cfac76_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email Address')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this subscriber still active?', verbose_name='Active Subscription')),
                ('unsubscribed_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, editable=False, null=True)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='core_newsle_email_c74825_idx'), models.Index(fields=['is_active', '-created_at'], name='core_newsle_is_acti_899c52_idx')],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this content visible to public? Uncheck to make draft.', verbose_name='Active/Published')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured items appear on homepage and special sections', verbose_name='Featured')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Lower numbers appear first (0 = highest priority)', verbose_name='Display Order')),
                ('customer_name', models.CharField(max_length=200, verbose_name='Customer Name')),
                ('customer_location', models.CharField(blank=True, help_text="e.g., 'New York, USA'", max_length=200, verbose_name='Location')),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='testimonials/', verbose_name='Customer Photo')),
                ('quote', models.TextField(help_text='Keep it short and powerful (max 500 chars)', max_length=500, verbose_name='Testimonial Quote')),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, verbose_name='Rating')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Testimonial',
                'verbose_name_plural': 'Testimonials',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this content visible to public? Uncheck to make draft.', verbose_name='Active/Published')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured items appear on homepage and special sections', verbose_name='Featured')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Lower numbers appear first (0 = highest priority)', verbose_name='Display Order')),
                ('category', models.CharField(choices=[('general', 'General'), ('booking', 'Booking & Reservations'), ('payment', 'Payment & Pricing'), ('destinations', 'Destinations'), ('travel', 'Travel Information'), ('safety', 'Safety & Health'), ('cancellation', 'Cancellation & Refunds')], db_index=True, default='general', max_length=50)),
                ('question', models.CharField(max_length=500, verbose_name='Question')),
                ('answer', models.TextField(verbose_name='Answer')),
                ('created_by', models.ForeignKey(blank=True, editable=False, help_text='User who created this entry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['category', 'order', 'question'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='core_faq_categor_181b73_idx')],
            },
        ),
    ]
