# Generated by Django 5.2.8 on 2026-07-03 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Account holder name as it appears at the bank', max_length=200),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='bank_swift',
            field=models.CharField(blank=True, max_length=50, verbose_name='Bank SWIFT / BIC'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_footer_note',
            field=models.TextField(blank=True, help_text='Optional note printed at the bottom of every invoice (terms, thank-you, etc.)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mpesa_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='M-Pesa account name'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mpesa_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='M-Pesa number / Lipa number'),
        ),
    ]
