# Generated by Django 5.2.8 on 2026-07-18 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_bank_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_signature',
            field=models.TextField(blank=True, help_text="Sign-off at the bottom of reply emails to customers (e.g. 'Warm regards,\\nMussa — Enteipa Adventures, Arusha'). Leave empty to use the site name (e.g. 'Enteipa Adventures Team')."),
        ),
    ]
