# Generated by Django 5.2.8 on 2026-07-18 13:59

from django.db import migrations


def admin_notes_to_notes(apps, schema_editor):
    """Preserve any existing single admin_notes text as a ContactNote."""
    ContactMessage = apps.get_model('core', 'ContactMessage')
    ContactNote = apps.get_model('core', 'ContactNote')
    for msg in ContactMessage.objects.exclude(admin_notes='').exclude(admin_notes__isnull=True):
        note = (msg.admin_notes or '').strip()
        if note:
            ContactNote.objects.create(
                contact_message=msg,
                body=note,
                created_at=msg.updated_at,
                updated_at=msg.updated_at,
            )


def noop(apps, schema_editor):
    # Reverse: leave copied notes in place (admin_notes still holds the original).
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactnote'),
    ]

    operations = [
        migrations.RunPython(admin_notes_to_notes, noop),
    ]
