# Generated by Django 5.2.8 on 2026-05-14 07:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Activity name (e.g., 'Morning Game Drive')", max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL slug', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the activity')),
                ('short_description', models.CharField(blank=True, help_text='Brief overview for cards/previews', max_length=500)),
                ('category', models.CharField(choices=[('safari', 'Safari & Wildlife'), ('hiking', 'Hiking & Trekking'), ('water_sports', 'Water Sports'), ('cultural', 'Cultural Tours'), ('adventure', 'Adventure Activities'), ('wildlife', 'Wildlife Viewing'), ('relaxation', 'Relaxation & Wellness'), ('photography', 'Photography Tours'), ('bird_watching', 'Bird Watching'), ('camping', 'Camping'), ('other', 'Other')], db_index=True, default='other', help_text='Activity category', max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], db_index=True, default='moderate', help_text='Difficulty level', max_length=20)),
                ('duration', models.DecimalField(decimal_places=1, help_text='Duration (e.g., 2.5)', max_digits=5, validators=[django.core.validators.MinValueValidator(0.5)])),
                ('duration_unit', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days')], default='hours', help_text='Duration unit (hours or days)', max_length=10)),
                ('min_age', models.PositiveIntegerField(blank=True, help_text='Minimum age requirement (optional)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)])),
                ('max_group_size', models.PositiveIntegerField(blank=True, help_text='Maximum group size (optional)', null=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Price per person in USD', max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(default='USD', help_text='Currency code (default: USD)', max_length=3)),
                ('featured_image', models.ImageField(blank=True, help_text='Main activity image', null=True, upload_to='activities/featured/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo video URL (optional)', null=True)),
                ('requirements', models.TextField(blank=True, help_text='What participants need (e.g., fitness level, equipment)')),
                ('included_items', models.TextField(blank=True, help_text="What's included in the activity")),
                ('excluded_items', models.TextField(blank=True, help_text="What's NOT included")),
                ('best_season', models.CharField(blank=True, help_text='Best time of year for this activity (optional)', max_length=255)),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Display as featured activity')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Published and visible to public')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times viewed')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title (optional, defaults to name)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities_created', to=settings.AUTH_USER_MODEL)),
                ('destination', models.ForeignKey(help_text='Destination where this activity is available', on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
                'ordering': ['order', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ActivityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image', upload_to='activities/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Image caption (optional)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='activities.activity')),
            ],
            options={
                'verbose_name': 'Activity Image',
                'verbose_name_plural': 'Activity Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['name'], name='activities__name_4db595_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['category', 'difficulty'], name='activities__categor_00d5d1_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['destination', 'is_active'], name='activities__destina_883bbe_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['is_featured', 'is_active'], name='activities__is_feat_83a0dc_idx'),
        ),
        migrations.AddIndex(
            model_name='activity',
            index=models.Index(fields=['order'], name='activities__order_31f2b4_idx'),
        ),
    ]
