# Generated by Django 5.2.8 on 2025-11-13 18:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0002_alter_accommodation_destination'),
        ('activities', '0001_initial'),
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('meta_title', models.CharField(blank=True, help_text='SEO-optimized title for search engines (max 60 chars recommended)', max_length=200, verbose_name='SEO Title')),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description for search engines (max 160 chars recommended)', max_length=500, verbose_name='SEO Description')),
                ('meta_keywords', models.CharField(blank=True, help_text="Comma-separated keywords for SEO (e.g., 'safari, tanzania, wildlife')", max_length=500, verbose_name='SEO Keywords')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Is this content visible to public? Uncheck to make draft.', verbose_name='Active/Published')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Featured items appear on homepage and special sections', verbose_name='Featured')),
                ('order', models.IntegerField(db_index=True, default=0, help_text='Lower numbers appear first (0 = highest priority)', verbose_name='Display Order')),
                ('view_count', models.PositiveIntegerField(default=0, editable=False, help_text='Number of times this item has been viewed', verbose_name='View Count')),
                ('name', models.CharField(help_text="Package name (e.g., '7-Day Serengeti Safari Adventure')", max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed package description')),
                ('short_description', models.CharField(help_text='Brief summary for listings', max_length=300)),
                ('highlights', models.TextField(blank=True, help_text='Key highlights (one per line or comma-separated)')),
                ('duration_days', models.PositiveIntegerField(help_text='Number of days', validators=[django.core.validators.MinValueValidator(1)])),
                ('duration_nights', models.PositiveIntegerField(help_text='Number of nights', validators=[django.core.validators.MinValueValidator(0)])),
                ('category', models.CharField(choices=[('adventure', 'Adventure'), ('luxury', 'Luxury'), ('family', 'Family'), ('honeymoon', 'Honeymoon'), ('group', 'Group'), ('budget', 'Budget'), ('wildlife', 'Wildlife Safari'), ('cultural', 'Cultural'), ('beach', 'Beach'), ('trekking', 'Trekking')], db_index=True, default='adventure', max_length=50)),
                ('difficulty_level', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], db_index=True, default='moderate', max_length=20)),
                ('group_size_min', models.PositiveIntegerField(default=1, help_text='Minimum group size', validators=[django.core.validators.MinValueValidator(1)])),
                ('group_size_max', models.PositiveIntegerField(default=12, help_text='Maximum group size', validators=[django.core.validators.MinValueValidator(1)])),
                ('price_per_person', models.DecimalField(decimal_places=2, help_text='Base price per person', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling')], default='USD', max_length=3)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0, help_text='Discount percentage (0-100)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('availability_status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('coming_soon', 'Coming Soon'), ('seasonal', 'Seasonal')], db_index=True, default='available', max_length=20)),
                ('start_date', models.DateField(blank=True, help_text='Package start date (for seasonal packages)', null=True)),
                ('end_date', models.DateField(blank=True, help_text='Package end date (for seasonal packages)', null=True)),
                ('max_bookings', models.PositiveIntegerField(default=10, help_text='Maximum number of bookings allowed')),
                ('current_bookings', models.PositiveIntegerField(default=0, help_text='Current number of bookings')),
                ('included_items', models.TextField(blank=True, help_text="What's included (one per line)")),
                ('excluded_items', models.TextField(blank=True, help_text="What's NOT included (one per line)")),
                ('requirements', models.TextField(blank=True, help_text="Requirements (e.g., 'Valid passport', 'Physical fitness')")),
                ('cancellation_policy', models.TextField(default='Full refund if cancelled 30 days before departure. 50% refund if cancelled 15-29 days before. No refund if cancelled within 14 days.', help_text='Cancellation and refund policy')),
                ('terms_and_conditions', models.TextField(blank=True, help_text='Terms and conditions')),
                ('featured_image', models.ImageField(blank=True, help_text='Main package image', null=True, upload_to='packages/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube or Vimeo video URL', null=True)),
                ('is_customizable', models.BooleanField(default=False, help_text='Can customers request custom modifications?')),
                ('booking_count', models.PositiveIntegerField(default=0, help_text='Total number of bookings')),
                ('rating_average', models.DecimalField(decimal_places=2, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('review_count', models.PositiveIntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packages_created', to=settings.AUTH_USER_MODEL)),
                ('destinations', models.ManyToManyField(help_text='Destinations included in this package', related_name='packages', to='destinations.destination')),
            ],
            options={
                'verbose_name': 'Package',
                'verbose_name_plural': 'Packages',
                'ordering': ['order', '-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('image', models.ImageField(upload_to='packages/gallery/')),
                ('caption', models.CharField(blank=True, max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='packages.package')),
            ],
            options={
                'verbose_name': 'Package Image',
                'verbose_name_plural': 'Package Images',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PackageInclusion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('inclusion_type', models.CharField(choices=[('accommodation', 'Accommodation'), ('activity', 'Activity'), ('transport', 'Transport'), ('meals', 'Meals'), ('guide', 'Guide'), ('equipment', 'Equipment'), ('insurance', 'Insurance'), ('visa', 'Visa'), ('other', 'Other')], default='other', max_length=50)),
                ('item_name', models.CharField(help_text="e.g., '4-star hotel accommodation'", max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description')),
                ('quantity', models.CharField(blank=True, help_text="e.g., '3 nights', '2 meals per day'", max_length=100)),
                ('is_included', models.BooleanField(default=True, help_text='True = Included, False = Excluded')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inclusions', to='packages.package')),
            ],
            options={
                'verbose_name': 'Package Inclusion',
                'verbose_name_plural': 'Package Inclusions',
                'ordering': ['package', 'is_included', 'order', 'inclusion_type'],
            },
        ),
        migrations.CreateModel(
            name='PackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('day_number', models.PositiveIntegerField(help_text='Day number', validators=[django.core.validators.MinValueValidator(1)])),
                ('title', models.CharField(help_text="Day title (e.g., 'Day 1: Arrival in Arusha')", max_length=200)),
                ('description', models.TextField(help_text='Detailed activities for this day')),
                ('breakfast_included', models.BooleanField(default=False)),
                ('lunch_included', models.BooleanField(default=False)),
                ('dinner_included', models.BooleanField(default=False)),
                ('highlights', models.CharField(blank=True, help_text='Key highlights for this day', max_length=500)),
                ('notes', models.TextField(blank=True, help_text="Optional notes (e.g., 'Early morning departure')")),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('accommodation', models.ForeignKey(blank=True, help_text='Where guests stay this night', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='package_itineraries', to='accommodations.accommodation')),
                ('activities', models.ManyToManyField(blank=True, help_text='Activities scheduled for this day', related_name='package_itineraries', to='activities.activity')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='packages.package')),
            ],
            options={
                'verbose_name': 'Package Itinerary',
                'verbose_name_plural': 'Package Itineraries',
                'ordering': ['package', 'day_number', 'order'],
            },
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['category', 'is_active'], name='packages_pa_categor_b32184_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['availability_status', 'is_active'], name='packages_pa_availab_5e2aec_idx'),
        ),
        migrations.AddIndex(
            model_name='package',
            index=models.Index(fields=['price_per_person'], name='packages_pa_price_p_bfe1c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='packageitinerary',
            unique_together={('package', 'day_number')},
        ),
    ]
