# Generated by Django 5.2.8 on 2025-11-14 21:04

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('inquiry_reference', models.CharField(editable=False, help_text='Auto-generated unique inquiry reference (e.g., INQ-2024-110001)', max_length=50, unique=True)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_phone', models.CharField(max_length=50)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('source', models.CharField(blank=True, help_text='How did they hear about us? (Google, Social Media, Friend, etc.)', max_length=100)),
                ('preferred_travel_date', models.DateField(blank=True, null=True)),
                ('flexible_dates', models.BooleanField(default=False, help_text='Are dates flexible?')),
                ('alternative_date_1', models.DateField(blank=True, null=True)),
                ('alternative_date_2', models.DateField(blank=True, null=True)),
                ('number_of_adults', models.PositiveIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1)])),
                ('number_of_children', models.PositiveIntegerField(default=0)),
                ('number_of_infants', models.PositiveIntegerField(default=0)),
                ('budget_range', models.CharField(choices=[('flexible', 'Flexible / Open Budget'), ('under_1000', 'Under $1,000'), ('1000_2000', '$1,000 - $2,000'), ('2000_3000', '$2,000 - $3,000'), ('3000_5000', '$3,000 - $5,000'), ('over_5000', '$5,000+'), ('specific', 'Specific Amount')], default='flexible', max_length=50)),
                ('specific_budget', models.DecimalField(blank=True, decimal_places=2, help_text="Specific budget per person (if budget_range = 'specific')", max_digits=10, null=True)),
                ('accommodation_preference', models.CharField(choices=[('budget', 'Budget Friendly'), ('standard', 'Standard'), ('luxury', 'Luxury'), ('ultra_luxury', 'Ultra Luxury')], default='standard', max_length=50)),
                ('dietary_requirements', models.TextField(blank=True, help_text='Any dietary restrictions')),
                ('special_requests', models.TextField(blank=True, help_text='Any special interests or requests')),
                ('prefer_email', models.BooleanField(default=True)),
                ('prefer_phone', models.BooleanField(default=False)),
                ('prefer_whatsapp', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending - New Inquiry'), ('reviewing', 'Reviewing - Staff Assigned'), ('quote_sent', 'Quote Sent - Awaiting Client'), ('negotiating', 'Negotiating - Discussion Ongoing'), ('approved', 'Approved - Client Confirmed'), ('payment_pending', 'Payment Pending'), ('converted', 'Converted to Booking'), ('declined', 'Declined by Client'), ('expired', 'Expired - No Response'), ('spam', 'Spam/Invalid')], default='pending', max_length=50)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', max_length=50)),
                ('staff_notes', models.TextField(blank=True, help_text='Internal staff notes (not visible to client)')),
                ('viewed_by_staff', models.BooleanField(default=False)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('base_package', models.ForeignKey(help_text='Original package customer is interested in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='packages.package')),
                ('staff_assigned', models.ForeignKey(blank=True, help_text='Staff member handling this inquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking Inquiry',
                'verbose_name_plural': 'Booking Inquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('custom_reference', models.CharField(editable=False, help_text='Unique reference (e.g., CUSTOM-2024-001)', max_length=50, unique=True)),
                ('access_token', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Secure token for client access')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Quote expiry date (typically 7 days)', null=True)),
                ('name', models.CharField(max_length=200)),
                ('short_description', models.TextField(max_length=500)),
                ('description', models.TextField()),
                ('duration_days', models.PositiveIntegerField()),
                ('duration_nights', models.PositiveIntegerField()),
                ('original_price', models.DecimalField(decimal_places=2, help_text='Original base package price per person', max_digits=10)),
                ('adjusted_price', models.DecimalField(decimal_places=2, help_text='Custom price per person after modifications', max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('modifications_made', models.TextField(blank=True, help_text='Summary of changes from base package')),
                ('staff_notes_to_client', models.TextField(blank=True, help_text='Personal message from staff to client (visible)')),
                ('staff_internal_notes', models.TextField(blank=True, help_text='Internal notes (not visible to client)')),
                ('status', models.CharField(choices=[('draft', 'Draft - Staff Working'), ('sent', 'Sent to Client'), ('viewed', 'Viewed by Client'), ('approved', 'Approved by Client'), ('rejected', 'Rejected by Client'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=50)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('first_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('last_viewed_at', models.DateTimeField(blank=True, null=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('client_feedback', models.TextField(blank=True, help_text="Client's comments/feedback on the package")),
                ('revision_number', models.PositiveIntegerField(default=1, help_text='Track how many times this was revised')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='packages/custom/')),
                ('base_package', models.ForeignKey(help_text='Base package used as template', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custom_versions', to='packages.package')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_custom_packages', to=settings.AUTH_USER_MODEL)),
                ('inquiry', models.ForeignKey(help_text='Original inquiry this package is for', on_delete=django.db.models.deletion.CASCADE, related_name='custom_packages', to='packages.bookinginquiry')),
                ('last_modified_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modified_custom_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Custom Package',
                'verbose_name_plural': 'Custom Packages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='bookinginquiry',
            name='custom_package',
            field=models.ForeignKey(blank=True, help_text='Custom package created for this inquiry', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_inquiry', to='packages.custompackage'),
        ),
        migrations.CreateModel(
            name='InquiryMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('sender_email', models.EmailField(blank=True, help_text='Email of sender (for client messages)', max_length=254)),
                ('sender_name', models.CharField(blank=True, help_text='Name of sender (for client messages)', max_length=200)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='inquiries/attachments/')),
                ('is_internal', models.BooleanField(default=False, help_text='Internal staff note (not visible to client)')),
                ('is_automated', models.BooleanField(default=False, help_text='Automated system message')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('inquiry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='packages.bookinginquiry')),
                ('sender_staff', models.ForeignKey(blank=True, help_text='Staff member who sent this (null = from client)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_inquiry_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inquiry Message',
                'verbose_name_plural': 'Inquiry Messages',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='custompackage',
            index=models.Index(fields=['status', '-created_at'], name='packages_cu_status_447856_idx'),
        ),
        migrations.AddIndex(
            model_name='custompackage',
            index=models.Index(fields=['inquiry', 'status'], name='packages_cu_inquiry_af79ac_idx'),
        ),
        migrations.AddIndex(
            model_name='custompackage',
            index=models.Index(fields=['access_token'], name='packages_cu_access__bac2d3_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinginquiry',
            index=models.Index(fields=['status', '-created_at'], name='packages_bo_status_c5e1b6_idx'),
        ),
        migrations.AddIndex(
            model_name='bookinginquiry',
            index=models.Index(fields=['staff_assigned', 'status'], name='packages_bo_staff_a_9e6f30_idx'),
        ),
    ]
