# Generated by Django 5.2.8 on 2026-05-14 11:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('departure_date', models.DateField(db_index=True)),
                ('max_seats', models.PositiveIntegerField(default=12)),
                ('booked_seats', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('available', 'Available'), ('sold_out', 'Sold Out'), ('cancelled', 'Cancelled')], db_index=True, default='available', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departures', to='packages.package')),
            ],
            options={
                'verbose_name': 'Departure',
                'verbose_name_plural': 'Departures',
                'ordering': ['departure_date'],
                'unique_together': {('package', 'departure_date')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='departure',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.departure'),
        ),
    ]
