# Generated by Django 5.2.8 on 2025-11-15 06:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_bookinginquiry_custompackage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageitinerary',
            name='end_day_number',
            field=models.PositiveIntegerField(blank=True, help_text='End day number (leave blank for single day, or set for day ranges like Days 3-7)', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='day_number',
            field=models.PositiveIntegerField(help_text='Start day number', validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='packageitinerary',
            name='description',
            field=models.TextField(help_text='Detailed activities for this day or period'),
        ),
    ]
