# Generated by Django 5.2.8 on 2026-05-14 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_availability_calendar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by', to='packages.package')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_packages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Package',
                'verbose_name_plural': 'Saved Packages',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'package')},
            },
        ),
    ]
