# Generated by Django 5.2.8 on 2025-11-15 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_packageitinerary_end_day_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPackageItinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('day_number', models.PositiveIntegerField()),
                ('end_day_number', models.PositiveIntegerField(blank=True, help_text='For multi-day ranges (e.g., Days 3-7)', null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=200)),
                ('accommodation_name', models.CharField(blank=True, max_length=200)),
                ('accommodation_type', models.CharField(blank=True, choices=[('hotel', 'Hotel'), ('lodge', 'Lodge'), ('camp', 'Tented Camp'), ('resort', 'Resort'), ('guesthouse', 'Guest House'), ('other', 'Other')], max_length=50)),
                ('activities', models.TextField(blank=True, help_text='Activities for this day')),
                ('breakfast_included', models.BooleanField(default=True)),
                ('lunch_included', models.BooleanField(default=True)),
                ('dinner_included', models.BooleanField(default=True)),
                ('transport_details', models.CharField(blank=True, max_length=200)),
                ('distance', models.CharField(blank=True, help_text='e.g., 120km', max_length=100)),
                ('drive_time', models.CharField(blank=True, help_text='e.g., 2-3 hours', max_length=100)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='custom_package_itinerary/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('custom_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itinerary_days', to='packages.custompackage')),
            ],
            options={
                'verbose_name': 'Custom Package Itinerary Day',
                'verbose_name_plural': 'Custom Package Itinerary Days',
                'ordering': ['order', 'day_number'],
                'unique_together': {('custom_package', 'day_number')},
            },
        ),
    ]
