# Generated by Django 5.2.8 on 2026-07-03 14:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_saved_package'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('invoice_number', models.CharField(db_index=True, editable=False, max_length=50, unique=True)),
                ('invoice_type', models.CharField(choices=[('deposit', 'Deposit Invoice'), ('balance', 'Balance Invoice'), ('full', 'Full Invoice')], default='deposit', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('customer_name', models.CharField(blank=True, max_length=200)),
                ('customer_email', models.EmailField(blank=True, max_length=254)),
                ('package_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True, help_text='Optional note shown on the invoice')),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='packages.booking')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issued_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['booking', '-created_at'], name='packages_in_booking_f412b1_idx')],
            },
        ),
    ]
