# Generated by Django 5.2.8 on 2026-05-14 00:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_custompackageitinerary'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('booking_reference', models.CharField(editable=False, max_length=50, unique=True)),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField(blank=True, null=True)),
                ('num_adults', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('num_children', models.PositiveIntegerField(default=0)),
                ('quoted_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('deposit_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('TZS', 'Tanzanian Shilling'), ('KES', 'Kenyan Shilling')], default='USD', max_length=3)),
                ('status', models.CharField(choices=[('pending_deposit', 'Pending Deposit'), ('deposit_paid', 'Deposit Paid'), ('confirmed', 'Confirmed - Fully Paid'), ('in_progress', 'In Progress - Trip Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending_deposit', max_length=20)),
                ('special_requirements', models.TextField(blank=True)),
                ('internal_notes', models.TextField(blank=True)),
                ('custom_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='packages.custompackage')),
                ('inquiry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking', to='packages.bookinginquiry')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bookings', to='packages.package')),
                ('staff_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Booking',
                'verbose_name_plural': 'Bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('dietary_requirements', models.CharField(blank=True, max_length=200)),
                ('medical_notes', models.TextField(blank=True)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=200)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=50)),
                ('is_lead_passenger', models.BooleanField(default=False)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passengers', to='packages.booking')),
            ],
            options={
                'verbose_name': 'Passenger',
                'verbose_name_plural': 'Passengers',
                'ordering': ['-is_lead_passenger', 'last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Automatically set when object is first created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Automatically updated whenever object is saved')),
                ('payment_type', models.CharField(choices=[('deposit', 'Deposit'), ('balance', 'Balance Payment'), ('full', 'Full Payment'), ('extra', 'Extra Charge'), ('refund', 'Refund')], default='deposit', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('mpesa', 'M-Pesa'), ('card', 'Credit / Debit Card'), ('stripe', 'Stripe (Online)'), ('other', 'Other')], default='bank_transfer', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed / Received'), ('refunded', 'Refunded'), ('failed', 'Failed')], db_index=True, default='confirmed', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='packages.booking')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status', '-created_at'], name='packages_bo_status_8d41c9_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['departure_date'], name='packages_bo_departu_c61f9f_idx'),
        ),
    ]
