# Generated by Django 5.2.8 on 2026-05-14 07:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Accommodation name', max_length=200, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='Auto-generated URL slug', max_length=200, unique=True)),
                ('description', models.TextField(help_text='Detailed description of the accommodation')),
                ('short_description', models.CharField(blank=True, help_text='Brief overview for cards/previews', max_length=500)),
                ('accommodation_type', models.CharField(choices=[('hotel', 'Hotel'), ('lodge', 'Lodge'), ('camp', 'Camp / Tented Camp'), ('resort', 'Resort'), ('guesthouse', 'Guesthouse'), ('hostel', 'Hostel'), ('villa', 'Villa'), ('apartment', 'Apartment'), ('boutique', 'Boutique Hotel'), ('other', 'Other')], db_index=True, default='hotel', help_text='Type of accommodation', max_length=50)),
                ('star_rating', models.IntegerField(blank=True, choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Star rating (1-5 stars)', null=True)),
                ('address', models.TextField(blank=True, help_text='Full address')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographic latitude (-90 to 90)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90.0), django.core.validators.MaxValueValidator(90.0)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='Geographic longitude (-180 to 180)', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180.0), django.core.validators.MaxValueValidator(180.0)])),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('email', models.EmailField(blank=True, help_text='Contact email', max_length=254)),
                ('website', models.URLField(blank=True, help_text='Official website URL')),
                ('amenities', models.TextField(blank=True, help_text="Comma-separated amenities (e.g., 'WiFi,Pool,Restaurant,Bar')")),
                ('price_per_night_min', models.DecimalField(blank=True, decimal_places=2, help_text='Minimum price per night', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('price_per_night_max', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum price per night', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling')], default='USD', help_text='Currency code (default: USD)', max_length=3)),
                ('featured_image', models.ImageField(blank=True, help_text='Main accommodation image', null=True, upload_to='accommodations/featured/')),
                ('video_url', models.URLField(blank=True, help_text='YouTube/Vimeo video URL (optional)', null=True)),
                ('total_rooms', models.PositiveIntegerField(blank=True, help_text='Total number of rooms', null=True)),
                ('check_in_time', models.CharField(blank=True, help_text="Check-in time (e.g., '2:00 PM')", max_length=50)),
                ('check_out_time', models.CharField(blank=True, help_text="Check-out time (e.g., '11:00 AM')", max_length=50)),
                ('policies', models.TextField(blank=True, help_text='Cancellation policies, rules, etc.')),
                ('is_featured', models.BooleanField(db_index=True, default=False, help_text='Display as featured accommodation')),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Published and visible to public')),
                ('view_count', models.PositiveIntegerField(default=0, help_text='Number of times viewed')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('meta_title', models.CharField(blank=True, help_text='SEO page title (optional, defaults to name)', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO meta description')),
                ('meta_keywords', models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accommodation',
                'verbose_name_plural': 'Accommodations',
                'ordering': ['order', '-is_featured', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AccommodationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Gallery image', upload_to='accommodations/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Image caption (optional)', max_length=200)),
                ('order', models.IntegerField(default=0, help_text='Display order')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Accommodation Image',
                'verbose_name_plural': 'Accommodation Images',
                'ordering': ['order', 'uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Room name/type', max_length=200)),
                ('room_type', models.CharField(choices=[('single', 'Single Room'), ('double', 'Double Room'), ('twin', 'Twin Room'), ('triple', 'Triple Room'), ('suite', 'Suite'), ('family', 'Family Room'), ('deluxe', 'Deluxe Room'), ('executive', 'Executive Room'), ('presidential', 'Presidential Suite')], default='double', help_text='Type of room', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Room description')),
                ('max_occupancy', models.PositiveIntegerField(default=2, help_text='Maximum number of guests')),
                ('bed_type', models.CharField(choices=[('single', 'Single Bed'), ('double', 'Double Bed'), ('queen', 'Queen Bed'), ('king', 'King Bed'), ('twin', 'Twin Beds'), ('bunk', 'Bunk Beds')], default='double', help_text='Type of bed(s)', max_length=50)),
                ('number_of_beds', models.PositiveIntegerField(default=1, help_text='Number of beds')),
                ('size_sqm', models.DecimalField(blank=True, decimal_places=2, help_text='Room size in square meters', max_digits=6, null=True)),
                ('price_per_night', models.DecimalField(decimal_places=2, help_text='Price per night', max_digits=10)),
                ('amenities', models.TextField(blank=True, help_text='Room-specific amenities (comma-separated)')),
                ('is_available', models.BooleanField(default=True, help_text='Currently available for booking')),
                ('image', models.ImageField(blank=True, help_text='Room image', null=True, upload_to='accommodations/rooms/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Room',
                'verbose_name_plural': 'Rooms',
                'ordering': ['accommodation', 'price_per_night'],
            },
        ),
    ]
