# Generated by Django 5.2.8 on 2025-11-10 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0001_initial'),
        ('destinations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Destination where this accommodation is located (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destinations.destination'),
        ),
    ]
