# Generated by Django 5.2.8 on 2026-05-14 07:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodations', '0001_initial'),
        ('destinations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accommodations_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accommodation',
            name='destination',
            field=models.ForeignKey(blank=True, help_text='Destination where this accommodation is located (optional)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destinations.destination'),
        ),
        migrations.AddField(
            model_name='accommodationimage',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='accommodations.accommodation'),
        ),
        migrations.AddField(
            model_name='room',
            name='accommodation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='accommodations.accommodation'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['name'], name='accommodati_name_a70e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['accommodation_type', 'star_rating'], name='accommodati_accommo_49a6d0_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['destination', 'is_active'], name='accommodati_destina_69bee5_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['is_featured', 'is_active'], name='accommodati_is_feat_c3e929_idx'),
        ),
        migrations.AddIndex(
            model_name='accommodation',
            index=models.Index(fields=['order'], name='accommodati_order_a62fa1_idx'),
        ),
    ]
