# Generated by Django 5.2.8 on 2025-11-16 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodations', '0002_alter_accommodation_destination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('GBP', 'British Pound'), ('KES', 'Kenyan Shilling'), ('TZS', 'Tanzanian Shilling')], default='USD', help_text='Currency code (default: USD)', max_length=3),
        ),
    ]
