"""
Phase 10.2 — Invoice model, PDF generation, dashboard views, and email tests.
"""
from decimal import Decimal

from django.contrib.auth import get_user_model
from django.core import mail
from django.core.cache import cache
from django.test import TestCase, Client
from django.urls import reverse

from core.models import SiteSettings
from packages.models import BookingInquiry, Invoice, Payment
from packages.tests import make_package, make_booking

User = get_user_model()


class InvoiceModelTests(TestCase):
    def setUp(self):
        self.package = make_package()
        self.inquiry = BookingInquiry.objects.create(
            base_package=self.package,
            customer_name='Amina Juma',
            customer_email='amina@example.com',
            customer_phone='0744123456',
        )
        self.booking = make_booking(self.package, inquiry=self.inquiry)

    def test_number_autogenerated_and_sequential(self):
        inv1 = Invoice.objects.create(booking=self.booking, invoice_type='deposit', amount=Decimal('600'))
        inv2 = Invoice.objects.create(booking=self.booking, invoice_type='balance', amount=Decimal('1800'))
        self.assertTrue(inv1.invoice_number.startswith('INV-'))
        self.assertNotEqual(inv1.invoice_number, inv2.invoice_number)
        # Sequence increments
        seq1 = int(inv1.invoice_number.split('-')[-1])
        seq2 = int(inv2.invoice_number.split('-')[-1])
        self.assertEqual(seq2, seq1 + 1)

    def test_snapshots_customer_and_package(self):
        inv = Invoice.objects.create(booking=self.booking, invoice_type='deposit', amount=Decimal('600'))
        self.assertEqual(inv.customer_name, 'Amina Juma')
        self.assertEqual(inv.customer_email, 'amina@example.com')
        self.assertEqual(inv.package_name, self.package.name)

    def test_snapshot_survives_inquiry_edit(self):
        inv = Invoice.objects.create(booking=self.booking, invoice_type='deposit', amount=Decimal('600'))
        self.inquiry.customer_name = 'Changed Name'
        self.inquiry.save()
        inv.refresh_from_db()
        self.assertEqual(inv.customer_name, 'Amina Juma')

    def test_issued_at_set_on_create(self):
        inv = Invoice.objects.create(booking=self.booking, invoice_type='full', amount=Decimal('2400'))
        self.assertIsNotNone(inv.issued_at)

    def test_booking_protected_from_delete(self):
        Invoice.objects.create(booking=self.booking, invoice_type='deposit', amount=Decimal('600'))
        from django.db.models import ProtectedError
        with self.assertRaises(ProtectedError):
            self.booking.delete()


class InvoicePdfTests(TestCase):
    def setUp(self):
        cache.delete(SiteSettings.CACHE_KEY)
        self.package = make_package()
        self.inquiry = BookingInquiry.objects.create(
            base_package=self.package,
            customer_name='Amina Juma',
            customer_email='amina@example.com',
            customer_phone='0744123456',
        )
        self.booking = make_booking(self.package, inquiry=self.inquiry)
        self.invoice = Invoice.objects.create(
            booking=self.booking, invoice_type='deposit', amount=Decimal('600'),
        )

    def tearDown(self):
        cache.delete(SiteSettings.CACHE_KEY)

    def test_render_produces_pdf_bytes(self):
        from packages.pdf import render_invoice_pdf
        pdf = render_invoice_pdf(self.invoice)
        self.assertTrue(pdf.startswith(b'%PDF-'))
        self.assertGreater(len(pdf), 1000)

    def test_pdf_includes_payment_details_when_configured(self):
        site = SiteSettings.load()
        site.mpesa_number = '0744000111'
        site.save()
        from packages.pdf import render_invoice_pdf
        # Should not raise; payment block is exercised
        pdf = render_invoice_pdf(self.invoice)
        self.assertTrue(pdf.startswith(b'%PDF-'))


class InvoiceViewTests(TestCase):
    def setUp(self):
        cache.delete(SiteSettings.CACHE_KEY)
        self.client = Client()
        self.staff = User.objects.create_user(username='invstaff', password='pass', is_staff=True)
        self.regular = User.objects.create_user(username='invcust', password='pass', is_staff=False)
        self.package = make_package()
        self.inquiry = BookingInquiry.objects.create(
            base_package=self.package,
            customer_name='Amina Juma',
            customer_email='amina@example.com',
            customer_phone='0744123456',
        )
        self.booking = make_booking(self.package, inquiry=self.inquiry)

    def tearDown(self):
        cache.delete(SiteSettings.CACHE_KEY)

    def test_create_requires_staff(self):
        url = reverse('packages:dashboard_invoice_create', args=[self.booking.pk])
        # anonymous
        resp = self.client.post(url, {'invoice_type': 'deposit', 'amount': '600', 'currency': 'USD'})
        self.assertIn(resp.status_code, [301, 302])
        self.assertEqual(Invoice.objects.count(), 0)
        # non-staff
        self.client.login(username='invcust', password='pass')
        resp = self.client.post(url, {'invoice_type': 'deposit', 'amount': '600', 'currency': 'USD'})
        self.assertIn(resp.status_code, [301, 302])
        self.assertEqual(Invoice.objects.count(), 0)

    def test_staff_creates_invoice(self):
        self.client.login(username='invstaff', password='pass')
        url = reverse('packages:dashboard_invoice_create', args=[self.booking.pk])
        resp = self.client.post(
            url, {'invoice_type': 'deposit', 'amount': '600', 'currency': 'USD'}
        )
        self.assertEqual(resp.status_code, 302)
        self.assertEqual(Invoice.objects.count(), 1)
        inv = Invoice.objects.first()
        self.assertEqual(inv.issued_by, self.staff)
        self.assertEqual(inv.customer_name, 'Amina Juma')

    def test_invalid_amount_rejected(self):
        self.client.login(username='invstaff', password='pass')
        url = reverse('packages:dashboard_invoice_create', args=[self.booking.pk])
        resp = self.client.post(
            url, {'invoice_type': 'deposit', 'amount': '0', 'currency': 'USD'}
        )
        self.assertEqual(resp.status_code, 302)
        self.assertEqual(Invoice.objects.count(), 0)

    def test_pdf_endpoint_returns_pdf(self):
        self.client.login(username='invstaff', password='pass')
        inv = Invoice.objects.create(booking=self.booking, invoice_type='deposit', amount=Decimal('600'))
        resp = self.client.get(reverse('packages:dashboard_invoice_pdf', args=[inv.pk]))
        self.assertEqual(resp.status_code, 200)
        self.assertEqual(resp['Content-Type'], 'application/pdf')
        self.assertTrue(resp.content.startswith(b'%PDF-'))

    def test_pdf_endpoint_requires_staff(self):
        inv = Invoice.objects.create(booking=self.booking, invoice_type='deposit', amount=Decimal('600'))
        resp = self.client.get(reverse('packages:dashboard_invoice_pdf', args=[inv.pk]))
        self.assertIn(resp.status_code, [301, 302])

    def test_email_endpoint_sends_with_attachment(self):
        self.client.login(username='invstaff', password='pass')
        inv = Invoice.objects.create(booking=self.booking, invoice_type='deposit', amount=Decimal('600'))
        resp = self.client.post(reverse('packages:dashboard_invoice_email', args=[inv.pk]))
        self.assertEqual(resp.status_code, 302)
        self.assertEqual(len(mail.outbox), 1)
        sent = mail.outbox[0]
        self.assertIn('amina@example.com', sent.to)
        self.assertEqual(len(sent.attachments), 1)
        filename, content, mimetype = sent.attachments[0]
        self.assertTrue(filename.endswith('.pdf'))
        self.assertEqual(mimetype, 'application/pdf')

    def test_booking_detail_shows_invoice_card_and_form(self):
        self.client.login(username='invstaff', password='pass')
        resp = self.client.get(reverse('packages:dashboard_booking_detail', args=[self.booking.pk]))
        self.assertEqual(resp.status_code, 200)
        self.assertContains(resp, 'Issue invoice')


class SettingsPaymentFieldsTests(TestCase):
    def setUp(self):
        cache.delete(SiteSettings.CACHE_KEY)
        self.client = Client()
        self.staff = User.objects.create_user(username='setpay', password='pass', is_staff=True)

    def tearDown(self):
        cache.delete(SiteSettings.CACHE_KEY)

    def test_settings_page_saves_payment_details(self):
        self.client.login(username='setpay', password='pass')
        resp = self.client.post(reverse('dashboard_settings'), {
            'whatsapp_number': '',
            'bank_name': 'CRDB Bank',
            'bank_account_name': 'Enteipa Tours',
            'bank_account_number': '0150123456789',
            'bank_swift': 'CORUTZTZ',
            'mpesa_name': 'Enteipa',
            'mpesa_number': '0744000111',
            'invoice_footer_note': 'Thank you for your business.',
        }, follow=True)
        self.assertEqual(resp.status_code, 200)
        site = SiteSettings.load()
        self.assertEqual(site.bank_name, 'CRDB Bank')
        self.assertEqual(site.mpesa_number, '0744000111')
        self.assertTrue(site.has_payment_details)
